// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPYuw-9WtSFpJhOlP4Jr-41VvH_vwKHxM',
    appId: '1:969441320766:web:c1e1a25fc1bac0e959966f',
    messagingSenderId: '969441320766',
    projectId: 'c-real-b35c8',
    authDomain: 'c-real-b35c8.firebaseapp.com',
    storageBucket: 'c-real-b35c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTDlVjLIvFK9SJmkc5yIkjB-XGn2dLV7M',
    appId: '1:969441320766:android:91d53f4a13d767ec59966f',
    messagingSenderId: '969441320766',
    projectId: 'c-real-b35c8',
    storageBucket: 'c-real-b35c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzxAIWMWLewur0aZwY1N-6sRF85KNzgFY',
    appId: '1:969441320766:ios:8c61dd932cab76e159966f',
    messagingSenderId: '969441320766',
    projectId: 'c-real-b35c8',
    storageBucket: 'c-real-b35c8.appspot.com',
    iosClientId: '969441320766-v3eqnajh8sipqfc01692j2l6qsuev3t7.apps.googleusercontent.com',
    iosBundleId: 'lydia.cReal',
  );
}